# Generated by Django 4.1.5 on 2023-02-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productsname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ss.productsname'),
            preserve_default=False,
        ),
    ]
