# Generated by Django 4.1.5 on 2023-02-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=200),
        ),
    ]
