# Generated by Django 4.1.6 on 2023-03-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0009_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(upload_to='static/images/orders'),
        ),
    ]
