# Generated by Django 4.1.6 on 2023-03-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0011_product_availability_product_brand_product_extras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
