# Generated by Django 4.1.6 on 2023-03-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0013_remove_product_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
