# Generated by Django 4.1.6 on 2023-03-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0015_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='offername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
