# Generated by Django 4.1.6 on 2023-03-18 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0017_offername_productsname'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offername',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ss.offername'),
            preserve_default=False,
        ),
    ]
