# Generated by Django 4.1.6 on 2023-03-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0019_product_offername'),
    ]

    operations = [
        migrations.CreateModel(
            name='suboffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss.offername')),
                ('productsname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss.productsname')),
            ],
        ),
    ]
