# Generated by Django 4.1.6 on 2023-03-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0022_product_suboffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='offername',
        ),
        migrations.RemoveField(
            model_name='category',
            name='suboffer',
        ),
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='otw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
