# Generated by Django 4.1.6 on 2023-03-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0023_orderdetailadmin_remove_category_offername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetailadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=5)),
                ('deliverypartner', models.CharField(max_length=50)),
                ('deliverydate', models.DateField()),
                ('trackid', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
