# Generated by Django 4.1.6 on 2023-03-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0024_orderdetailadmin_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='size',
            new_name='sizee',
        ),
    ]
