# Generated by Django 4.1.6 on 2023-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0026_rename_sizee_order_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='sizee',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
