# Generated by Django 4.1.6 on 2023-03-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0034_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
    ]
