# Generated by Django 4.1.6 on 2023-03-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0038_alter_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pay_id',
        ),
    ]
