# Generated by Django 4.1.6 on 2023-03-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0039_remove_payment_pay_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='orderid',
        ),
    ]
