# Generated by Django 4.1.6 on 2023-03-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0040_rename_order_id_payment_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
