# Generated by Django 4.1.6 on 2023-03-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0042_remove_product_size_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='image',
            field=models.ImageField(default=1, upload_to='static/images/orders'),
            preserve_default=False,
        ),
    ]
