# Generated by Django 4.1.6 on 2023-03-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0044_variant_delete_orderplaced'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variant',
            new_name='unitproduct',
        ),
        migrations.RenameField(
            model_name='unitproduct',
            old_name='variantname',
            new_name='sisename',
        ),
    ]
