# Generated by Django 4.1.6 on 2023-03-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0045_rename_variant_unitproduct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='unitproduct',
        ),
    ]
